trapping

diff --git a/Ass1/matrix b/Ass1/matrix
--- a/Ass1/matrix
+++ b/Ass1/matrix
@@ -1,6 +1,9 @@
 #!/bin/bash
 #Matrix
 
+# exit when anything fails
+set -e
+
 function uponExit(){
 	rm -f *.tmp
 }
@@ -21,6 +24,46 @@ TMPRow="temprow$$.tmp"
 }
 
 tempCreate
+
+# Functions to check the number of arguments and if they exist.
+
+function fileExists(){
+# Check if all of the arguments files exist
+# See https://stackoverflow.com/questions/255898/how-to-iterate-over-arguments-in-a-bash-script
+# for reference
+for var in "$@"
+do
+	if [ ! -f "$var" ]; then
+		echo "File does not exist" 1>&2
+		return 1
+	fi
+done
+}
+
+function oneArgument(){
+if [ $# -gt 1 ]; then
+	echo "illegal number of parameters" 1>&2
+	return 1
+fi
+
+#Now check if the file exists
+fileExists "$@"
+
+}
+
+function twoArgument(){
+if [ $# -ne 2 ]; then
+	echo "illegal number of parameters" 1>&2
+	return 1
+fi
+
+#Now check if the file exists
+fileExists "$@"
+
+}
+
+
+
 
 function stdinSave(){
 # NAME: stdinSave - Save a matrix to a temporary file
@@ -87,6 +130,10 @@ echo $outOne
 }
 
 function mean(){
+
+#First Check the number of arguments and if they exists
+oneArgument "$@"
+
 stdinSave $1
 
 #First, find the number of columns in the file.
@@ -108,13 +155,20 @@ for ((i=1; i<=$nCols; i++))
 			echo
 		fi
 	done
+return 1
 }
 
 
 function dims(){
+
+#First Check the number of arguments and if they exists
+oneArgument "$@"
+
+# Save the Input to a matrix
 stdinSave $1
 
 echo "$nCols $nRows"
+return 0
 }
 
 function transposeHelp(){
@@ -146,6 +200,10 @@ echo -n -e "\n" >> $output
 }
 
 function transpose(){
+
+#First Check the number of arguments and if they exists
+oneArgument "$@"
+
 stdinSave $1
 for ((i=1; i<=$nCols; i++))
 	do
@@ -153,6 +211,7 @@ for ((i=1; i<=$nCols; i++))
 		transposeHelp $TMPCol $TMPTwo
 	done
 cat "$TMPTwo"
+return 0
 }
 
 function addAndAppend(){
@@ -202,6 +261,9 @@ function add(){
 # GENERAL DESCRIPTION: Saves each row to a temporary file, adds the two files together
 # and appends results to a third temporary file, then displays the end result.
 
+#First Check the number of arguments and if they exists
+twoArgument "$@"
+
 loadTwoMatrices $1 $2
 
 for ((i=1; i<=$nRowOne; i++))
@@ -211,6 +273,7 @@ for ((i=1; i<=$nRowOne; i++))
 		addAndAppend $TMPTwo $TMPThree $TMP $nColOne
 	done
 cat $TMP
+return 0
 }
 
 function multiplyHelper(){
@@ -239,6 +302,9 @@ function multiply(){
 # General Description Break off the column of one matrix, convert it
 # to a row file, and then multiply them together
 
+#First Check the number of arguments and if they exists
+twoArgument "$@"
+
 # First Transpose the first matrix
 transpose $2 > $TMPRow
 
@@ -266,6 +332,7 @@ for ((i=1; i<=$nRowOne; i++))
 		done
 	done
 cat $TMP
+return 0
 }
 
 $1 "${@:2}"
